spring.application.name=TrujillanosSAC
server.port=9191

spring.datasource.url=jdbc:oracle:thin:@//34.229.249.155:1521/orcl
spring.datasource.username=eltrujillano
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.jdbc.fetch_size=100
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.open-in-view=false
spring.thymeleaf.check-template-location=false
